version: '0.2'
language: en
words:
- alppa
- beautysh
- chrono
- codespell
- consteval
- constexpr
- constinit
- cppcheck
- cppreference
- CRTP
- decltype
- deque
- EDITMSG
- frontmatter
- glvalue
- ifdef
- Liskov
- lldb
- lvalue
- mdformat
- Metaprogramming
- Microbenchmarking
- noexcept
- NRVO
- nullptr
- Postconditions
- prvalue
- pyenv
- pyproject
- RAII
- Rvalue
- SFINAE
- Stroustrup
- TSAN
- valgrind
- venv
- vtables
- xvalue
