version: "0.2"
language: en
words:
  - beautysh
  - chrono
  - codespell
  - consteval
  - constexpr
  - constinit
  - cppcheck
  - cppreference
  - CRTP
  - decltype
  - deque
  - EDITMSG
  - frontmatter
  - glvalue
  - ifdef
  - Liskov
  - lldb
  - lvalue
  - maxlevel
  - mdformat
  - metaprogramming
  - microbenchmarking
  - minlevel
  - noexcept
  - NRVO
  - nullptr
  - postconditions
  - prvalue
  - pyenv
  - pyproject
  - RAII
  - rvalue
  - SFINAE
  - Stroustrup
  - TSAN
  - valgrind
  - venv
  - vtables
  - xvalue
