version: '0.2'
language: en
words:
- beautysh
- chrono
- codespell
- consteval
- constexpr
- constinit
- coro
- cppcheck
- cppreference
- CRTP
- decltype
- defop
- deque
- EDITMSG
- frontmatter
- glvalue
- hier
- ifdef
- jthread
- Liskov
- lldb
- longjmp
- lvalue
- maxlevel
- mdformat
- Metaprogramming
- Microbenchmarking
- minlevel
- noexcept
- NRVO
- nullptr
- Postconditions
- prvalue
- pyenv
- pyproject
- RAII
- Rvalue
- setjmp
- SFINAE
- stringstream
- Stroustrup
- TSAN
- valgrind
- venv
- vtables
- xvalue
