repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        args: [ --number, --wrap, "100" ]
        additional_dependencies:
          - mdformat-beautysh
          - mdformat-black
          - mdformat-config
          - mdformat-frontmatter
          - mdformat-footnote
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-pyproject
          - mdformat-simple-breaks
          - mdformat-toc
          - mdformat-tables
        language_version: python3.10
